### ISSUE TITLE
Not an issue, sharing my build 

### ISSUE THREAD

**Issue by Leerz** [stooged/PS4-Server-900u#14]
![20220125_012843_HDR](https://user-images.githubusercontent.com/9525365/150837625-043226a2-72a6-4f2e-8a3e-3dd81a752f6b.jpg)
![20220125_015443_HDR](https://user-images.githubusercontent.com/9525365/150837637-d6cbde97-79bf-4703-b9a1-5843aaae1218.jpg)

managed to cram inside those prevalent ps4 payload dongles which are cheap esp8266 
autoboots goldhen

plug in once, 
connect to APN once 
user guide or browser upon boot 

??!!! 

profit 

Thank you!

**Comment by stooged** [comment]
nice work.
