### ISSUE TITLE
Esp32 with control usb

### ISSUE THREAD

**Issue by EdwardDanielSalazar** [stooged/PS4-Server-900u#18]
Hello, Would you be so kind to port that for ESP32 as well? With control usb, the board original wihtouth S2, thanks

**Comment by stooged** [comment]
the esp32 has a port for usb control

you need to set autousb to true and define the gpio pin you are going to use then usb control will be active.

```
#define AUTOUSB true // set to true if you are using usb control
#define usbPin 4  // set the pin you want to use for usb control
```
https://github.com/stooged/ESP32-Server-900/blob/main/ESP32_Server_900/ESP32_Server_900.ino#L8
