### ISSUE TITLE
Little question about resistors 

### ISSUE THREAD

**Issue by Klairm** [stooged/PS4-Server-900u#21]
Hello, I'm learning a litle about electronics, and I have a doubt on why the NPN transistor needs the resistor on the base and on the GND cable of the USB? 

Thanks

**Comment by stooged** [comment]
https://forum.arduino.cc/t/why-do-we-need-a-resistor-connected-to-the-base-of-the-transistor/208051

**Comment by Klairm** [comment]
> https://forum.arduino.cc/t/why-do-we-need-a-resistor-connected-to-the-base-of-the-transistor/208051

thanks a lot
