### ISSUE TITLE
not exactly an issue

### ISSUE THREAD

**Issue by Leerz** [stooged/PS4-Server-900u#3]
could it be programmatically done to divert the DATA + (or even DAT -)  line of the flashdrive to a GPIO d7 and throw it to d8 ON  trigger instead of using a relay? 

probably a stupid question but IDK

**edit
i searched online but it seemed to say not possible

**Comment by stooged** [comment]
no i do not think that is possible but a similar thing has been achieved here using a npn transistor on the D+ line

https://www.psxhax.com/threads/ps4-server-9-00-ps4-server-9-00u-for-esp8266-d1-mini-pro-by-stooged.10685/post-192151
