### ISSUE TITLE
NOT AN ISSUE, A question sorry

### ISSUE THREAD

**Issue by Doyle4** [stooged/PS4-Server-900u#4]
Hi there,

managed to compile and worked on my ESP, although it says how to upload payloads im unsure on this step.
I use a mac and under Tools is no Sketch, there is a Sketch submenu, but no load data.

Any help would be amazing on this thanks.

**Comment by Leerz** [comment]
go to ip/admin.html and upload the payload goldhen
also, you need to install the esp8266 sketch spi tool thinggy to show on arduino

**Comment by Doyle4** [comment]
Thank you, will give that a try.

I have that installed along with a few others, think its because its a mac version, I'll try the windows version when I get it back installed on my machine, other than not able to upload the .bins, everything else seems great thanks.

**Comment by stooged** [comment]
https://github.com/esp8266/arduino-esp8266fs-plugin#installation

it has the os x install information in the readme.

**Comment by Doyle4** [comment]
All working good thanks.

Misunderstanding on the Sketch message. When home page launched, the no payloads message mentions about uploading them with Arduino IDE, this is what confused me. Iv changed the message uploading them with sketch to esp-ip/admin.html.

Thanks again, great work!

**Comment by Doyle4** [comment]
![Screenshot 2022-01-04 at 13 38 44](https://user-images.githubusercontent.com/65953502/148067523-0e929d74-2c3f-4125-a77b-981b1eaf554a.png)

This is the message I have been referring too.

For others who are stuck here also, As stooged says, goto 10.1.1.1 (or set ip you chose)/admin.html, there is where you can upload your payloads, hope this helps.
