### ISSUE TITLE
Loader.h

### ISSUE THREAD

**Issue by peyman4774** [stooged/PS4-Server-900u#6]
Hi,
i got too many kp or kernel heap on usb sleep time 10000 ms.
changed to 15000 ms  & no more kp
tested on 2 ps4
usb 2 & usb3
@Leerz

**Comment by stooged** [comment]
added the ability to adjust the wait time in the config editor as different usb devices have different load times.
the default is still 10000ms but you can change that to a value between 5000 and 25000.
